version: '3.7'
services:
  backend:
    build: ./backend
    ports:
      - 8003:8000
    volumes:
      - ./backend:/usr/src/app
    restart: always
    ipc: host
    # local DB
    environment:
      - DB_HOST=192.168.1.13
      - DB_NAME=work
      - DB_USER=root
      - DB_PW=mysql
      - TZ=Asia/Seoul
      - EXT_HOST=10.10.10.11
      - EXT_PORT=84
      - EMERGENCY_PROPERTY=122
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    #command: gunicorn deeplounge_a_renewal.wsgi:application --bind 0.0.0.0:8000

  frontend:
    build: ./frontend
    ports:
      - 3003:3000
    volumes:
      - ./frontend:/usr/src/app
    restart: always
    ipc: host
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Asia/Seoul
    # command: tail -F /dev/null
    command: npm start

  revers_proxy:
    build: ./nginx
    ports:
      - 84:80
    depends_on:
      - backend
      - frontend
    restart: always
